services:
  ruby:
    build:
      - echo "prepare service 1"
      - echo "prepare service 2"
      - gem install foreman
    from: 'ruby:2.2.3'

defaults: &defaults
  prepare:
    - ls -alh websocket-demo
    - env
    - gem list
  service: ruby
  folder: /app

staging:
  <<: *defaults
  ports:
   - 3001
   - 3002
  cmd: foreman start
  env:
    - RACK_ENV=production

tests:
  <<: *defaults
  cmd: 'for i in {1..100}; do printf "."; sleep 0.1; done; printf "\n";'
  env:
    - RACK_ENV=test
