services:
  ruby:
    from: 'ruby:2.2.3'
    build:
      - 'gem install foreman'
      - 'curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -'
      - 'sudo apt-get install -y nodejs'

defaults: &defaults
  service: ruby
  folder: /app

# staging:
#   <<: *defaults
#   ports:
#    - 3001
#    - 3002
#   cmd: foreman start
#   env:
#     - NODE_ENV=production
#     - RACK_ENV=production

tests:
  <<: *defaults
  cmd: "echo '..........................................................'"
  env:
    - RACK_ENV=test
    - NODE_ENV=test
