services:
  ruby:
    prepare:
      - echo "prepare service 1"
      - echo "prepare service 2"
    from: 'ruby:2.2.3'

staging:
  prepare:
    - echo "prepare victim"
  service: ruby
  folder: /app
  port: 3000
  cmd: 'ruby -run -e httpd . -p 3000'
  env:
    - RACK_ENV=production

tests:
  prepare:
    - echo "prepare victim"
  service: ruby
  folder: /app
  cmd: 'echo "..............................."'
  env:
    - RACK_ENV=production
