services:
  ruby:
    from: 'ruby:2.2.3'
    build:
      - 'gem install foreman'
      - '/bin/sh -lc "curl -sL https://deb.nodesource.com/setup_4.x | bash -"'
      - 'apt-get update'
      - 'apt-get install -y build-essential nodejs'

defaults: &defaults
  service: ruby
  folder: /app
  prepare:
    - 'node -v'
    - "echo 'this is prepare section'"
    - "echo '.'"

staging:
  <<: *defaults
  ports:
   - 3001
   - 3002
  cmd: foreman start
  env:
    - NODE_ENV=production
    - RACK_ENV=production

tests:
  <<: *defaults
  cmd: "echo '..'"
  env:
    - NODE_ENV=production
    - RACK_ENV=production
