services:
  ruby:
    from: 'ruby:2.2.3'
    prepare:
      - gem install foreman

defaults: &defaults
  prepare:
    - ls -alh websocket-demo
    - env
    - gem list
  service: ruby
  folder: /app
  env:
    - RACK_ENV=production

staging:
  <<: *defaults
  ports:
   - 3001
   - 3002
  cmd: foreman start

tests:
  <<: *defaults
  cmd: 'echo "..............................."'
