services:
  ruby:
    prepare:
      - echo "prepare service 1"
      - echo "prepare service 2"
    from: 'ruby:2.2.3'

defaults: &server
  prepare:
    - echo "prepare victim"
  service: ruby
  folder: /app
  env:
    - RACK_ENV=production

staging:
  port: 3001
  cmd: 'ruby -run -e httpd . -p 3001'

tests:
  cmd: 'echo "..............................."'
