services:
  ruby:
    from: 'ruby:2.2.3'
    prepare:
      - gem install foreman
      - echo "prepare service 1"
      - echo "prepare service 2"

defaults: &server
  prepare:
    - git --version
    - ls -alh websocket-demo
    - env
    - echo "prepare victim"
  service: ruby
  folder: /app
  env:
    - RACK_ENV=production

staging:
  <<: *server
  ports: [3001, 3002]
  cmd: foreman start

tests:
  <<: *server
  cmd: 'echo "..............................."'
